# Generated by Django 3.1.3 on 2021-01-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201228_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descrip',
            field=models.CharField(default='Write description...', max_length=500),
        ),
    ]
